### ISSUE TITLE
Close streams properly

### ISSUE THREAD

**Issue by xmedeko** [davidzof/wattzap-ce#85]
When reading files, RLV, TTS, ... close the streams properly in a `try` block, e.g. see http://www.oracle.com/technetwork/articles/java/trywithresources-401775.html 
(Java 6 `try .. finally`, Java 7 has a new `try ()` construct).

**Comment by davidzof** [comment]
Quite right!

I've done a code review
1. GPX Reader
uses the GPXFile class which handles file opening and closing files itself.
2. RLV Reader
This accesses two files: an RLV file and a PGMF file
The RLV method correctly closes the file in the finally block. It is closed via the DataInputStream wrapper which will call the wrapped FileInputStream.
The PGMF code has the close in the try block. Fixed in the method readPGMF()
3. TTSReader
Just passes the exception up the method call stack. Should at least have a try/finally block. Fixed in parseFile() method
